import React from "react";
import { Link, useParams } from "react-router-dom";
import styled, { createGlobalStyle } from "styled-components";
import { colors, siteDiary } from "../constants";
import DiaryEntryCard from "../components/DiaryEntryCard";
import Heading from "../components/Heading";
import DiaryLayout from "../components/DiaryLayout";

//TODO: Make sure using all data fro
//TODO: Update weather to be better...
//TODO: Change all colours to use this
//TODO: Go through all styles generated by chatgpt and clean up
//TODO: Add a back button to go back to the diary entries page
const BackgroundGlobalStyle = createGlobalStyle`
  body, html {
    margin: 0;
    height: 100%;
    background-color: ${colors.lightest};
  }

  #root {
    height: 100%;
  }
`;

const DiaryEntry: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const entry = siteDiary.find((entry) => entry.id === id);

  //TODO: Improve this error handling
  if (!entry) {
    return <div>No entry found</div>;
  }

  return (
    <DiaryLayout>
      <BackgroundGlobalStyle />
      <Heading text={entry.title} />
      <DiaryEntryCard {...entry} />
    </DiaryLayout>
  );
};

export default DiaryEntry;
